version: "3.9"

networks:
  gateway:
    external: true
    name: "gateway"

services:
  libretranslate:
    container_name: libretranslate
    image: nexus.lab.local:8083/libretranslate:arm64
    volumes:
      - "$INSTALL_DIR/local:/home/libretranslate/.local:rw"
    restart: unless-stopped
    networks:
      - gateway
